### ISSUE TITLE
Update fails on diff geomtrey

### ISSUE THREAD

**Issue by frodrigo** [makina-maps/makina-maps#36]
```
ERROR:  Geometry type (MultiPolygon) does not match column type (Polygon)
STATEMENT:  INSERT INTO "public"."osm_aeroway_polygon_gen2" (SELECT "ref",
      "osm_id",
      ST_SimplifyPreserveTopology("geometry", 38.218514) as "geometry",
      "aeroway",
      "area" FROM "public"."osm_aeroway_polygon" WHERE "osm_id" = $1 AND (area>power(76.43702828517628,2)))
```

The issue come from OpenMapTiles. Geometry type have to be casted on Table and view creation from SELECT.

**Comment by frodrigo** [comment]
Same as https://github.com/openmaptiles/openmaptiles/issues/1018

**Comment by frodrigo** [comment]
PR on imposm done https://github.com/omniscale/imposm3/pull/263

**Comment by amenk** [comment]
I believe this issue is no longer happening in recent OpenMapTiles versions? 

See here: https://github.com/omniscale/imposm3/pull/271

Or can you still reproduce this issue?

Otherwise we should update the OpenMapTiles submodule in makina-maps to the latest version?

Because the current version still seems to break the installation from scratch in #52

**Comment by frodrigo** [comment]
It is fixed on imposm, and now on OpenMapTiles.

Nevertheless, still need to update the OpenMapTiles version on Makina Maps. I am working on it.

**Comment by frodrigo** [comment]
OpenMapTiles project is now update, using the fixed imposm version.

**Comment by amenk** [comment]
@frodrigo Thank you so much, will try it at the weekend.

**Comment by amenk** [comment]
The setup works well now
