### ISSUE TITLE
Import hardly any street names

### ISSUE THREAD

**Issue by goody85** [makina-maps/makina-maps#55]
Hi followed all steps works wonderfully unitil zooming in to find there are no street names.

In the yaml files tranport layers are there
Dont think the street name data has been imported to postgres

How can i resolve this?
Very limited experience with this

**Comment by amenk** [comment]
1. Are they no street names or only a few?
2. Which area did you import? Which coordinates / streets are you looking at? I could imagine some problem with local translations, but this is just a guess.
3. Which version of makina-maps are you using? Did you clone it recently?

You can access the database with 
```
cd openmaptiles
make psql
```

But I am not sure in which table the street names should go, as I was not able to set it up correctly.

**Comment by amenk** [comment]
@goody85 

so you solved the problem of missing openmaptiles-tools by switching to another branch? Not sure if that can be the reason. There is a issue #52 which is closed, but I believe this still needs to be fixed.
Unfortunately due to the missing openmaptiles-tools I currently cannot reproduce the problem.

With the last command (database access) you could look around in the database if the street names were imported at all.
Unfortunately I do not know which tables the street names should be stored in.

With `\dt` you can see the tables, with `select * from table_name_goes_here` you can view the single tables. The should be something like `transport_name` tables and so on.

It might be best to wait until the problem mit openmaptiles-tools is fixed? Or maybe someone else has some advice ...

**Comment by goody85** [comment]
I found a resolve with it.

As i followed the instructions, coming to the import openmaptiles tools
were missing, so i grabbed a copy , but got the wrong version i didnt look
down the branch for yours. 5.2

Thank you for your help 😊
